CREATE TYPE "public"."report_status" AS ENUM('Draft', 'Finalized', 'Under Review', 'Rejected', 'Archived');--> statement-breakpoint
CREATE TABLE "doctor_patient" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "doctor_patient_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"doctor_id" uuid,
	"patient_id" uuid,
	"order_no" bigint
);
--> statement-breakpoint
CREATE TABLE "organization" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255),
	"address" varchar(512),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"image_url" text
);
--> statement-breakpoint
CREATE TABLE "organization_patient" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "organization_patient_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" uuid DEFAULT gen_random_uuid(),
	"organization_id" uuid DEFAULT gen_random_uuid(),
	"status" varchar,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "organization_staff" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid,
	"staff_id" uuid,
	"role_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sample_image_ai" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"original_sample_image_id" uuid,
	"image_url" text
);
--> statement-breakpoint
ALTER TABLE "annotation" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "note" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "session" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "test_sample" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "annotation" CASCADE;--> statement-breakpoint
DROP TABLE "note" CASCADE;--> statement-breakpoint
DROP TABLE "session" CASCADE;--> statement-breakpoint
DROP TABLE "test_sample" CASCADE;--> statement-breakpoint
ALTER TABLE "patient" DROP CONSTRAINT "patient_note_id_unique";--> statement-breakpoint
ALTER TABLE "patient" DROP CONSTRAINT "patient_note_id_note_id_fk";
--> statement-breakpoint
ALTER TABLE "image" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "patient" ALTER COLUMN "birth_date" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "patient" ALTER COLUMN "contact_number" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "patient" ALTER COLUMN "email" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "patient" ALTER COLUMN "address" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "patient" ALTER COLUMN "height" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "patient" ALTER COLUMN "weight" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "patient" ALTER COLUMN "blood_type" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "profile" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "report" ALTER COLUMN "content" SET DATA TYPE jsonb;--> statement-breakpoint
ALTER TABLE "report" ALTER COLUMN "export_format" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "auth"."users" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "patient" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "profile" ADD COLUMN "license_no" text;--> statement-breakpoint
ALTER TABLE "profile" ADD COLUMN "must_change_password" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "report" ADD COLUMN "title" text;--> statement-breakpoint
ALTER TABLE "report" ADD COLUMN "patient_id" uuid;--> statement-breakpoint
ALTER TABLE "report" ADD COLUMN "test_type" text;--> statement-breakpoint
ALTER TABLE "report" ADD COLUMN "status" "report_status";--> statement-breakpoint
ALTER TABLE "report" ADD COLUMN "code" text;--> statement-breakpoint
ALTER TABLE "report" ADD COLUMN "organization_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "sample" ADD COLUMN "organization_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "sample" ADD COLUMN "created_at" timestamp DEFAULT now();--> statement-breakpoint
ALTER TABLE "organization_staff" ADD CONSTRAINT "organization_staff_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "organization_staff" ADD CONSTRAINT "organization_staff_staff_id_profile_id_fk" FOREIGN KEY ("staff_id") REFERENCES "public"."profile"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "organization_staff" ADD CONSTRAINT "organization_staff_role_id_role_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."role"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sample_image_ai" ADD CONSTRAINT "sample_image_ai_original_sample_image_id_sample_image_id_fk" FOREIGN KEY ("original_sample_image_id") REFERENCES "public"."sample_image"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "patient" ADD CONSTRAINT "patient_created_by_profile_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."profile"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "report" ADD CONSTRAINT "report_patient_id_patient_id_fk" FOREIGN KEY ("patient_id") REFERENCES "public"."patient"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "report" ADD CONSTRAINT "report_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sample" ADD CONSTRAINT "sample_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "patient" DROP COLUMN "note_id";